In [ ]:
import numpy as np
### 2.1: Creating Arrays

# From Python list
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  # [1 2 3 4 5]

# 2D array (matrix)
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr2d)

# Zeros array (all zeros)
zeros = np.zeros(5)  # [0. 0. 0. 0. 0.]

# Ones array (all ones)
ones = np.ones((3, 3))  # 3x3 matrix of ones

# Range array (like Python range)
range_arr = np.arange(0, 10, 2)  # [0 2 4 6 8]

# Linspace (evenly spaced values)
linspace_arr = np.linspace(0, 1, 5)  # [0.   0.25 0.5  0.75 1.  ]

# Random values
random_arr = np.random.rand(5)  # [0.45 0.23 0.89 ...]

# Identity matrix
identity = np.eye(3)  # 3x3 identity matrix

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
### 2.2: Array Properties

arr = np.array([1, 2, 3, 4, 5])

# Shape (dimensions)
print(arr.shape)  # (5,) - 1D array with 5 elements

# Size (total elements)
print(arr.size)  # 5

# Data type
print(arr.dtype)  # int64 or int32

# Reshape
reshaped = arr.reshape(5, 1)  # Convert to column
print(reshaped.shape)  # (5, 1)

# 2D example
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.shape)  # (2, 3) -> 2 rows, 3 columns


(5,)


In [ ]:
## Step 3: Array Operations (Vectorization)

### 3.1: Basic Math (Element-wise)


arr = np.array([1, 2, 3, 4, 5])

# Add scalar -> add to each element
result = arr + 10  # [11 12 13 14 15]

# Multiply -> multiply each element
result = arr * 2   # [2 4 6 8 10]

# Square root -> must use np.sqrt()
result = np.sqrt(arr)  # [1. 1.41 1.73 2. 2.24]

# Power
result = arr ** 2  # [1 4 9 16 25]

# Why this matters:
# Instead of: for i in range(len(arr)): arr[i] = arr[i] * 2
# You can:    arr = arr * 2  (MUCH faster!)


In [ ]:
### 3.2: Array to Array Operations

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result = arr1 + arr2  # [5 7 9]

# Multiplication
result = arr1 * arr2  # [4 10 18]

# Broadcasting (when shapes don't match)
arr1 = np.array([[1, 2, 3]])  # shape (1, 3)
arr2 = np.array([[1], [2], [3]])  # shape (3, 1)

# Broad cast =  Rule: If one array has a 1 or fewer dimensions, stretch it to match the other.

# That's it. Broadcasting = automatic stretching.
result = arr1 + arr2  # Broadcasts to (3, 3)!
# [[2 3 4]
#  [3 4 5]
#  [4 5 6]]

In [6]:
### 3.3: Common Functions


arr = np.array([1, 5, 3, 2, 4])

# Sum
print(np.sum(arr))  # 15

# Mean (average)
print(np.mean(arr))  # 3.0

# Min/Max
print(np.min(arr))  # 1
print(np.max(arr))  # 5

# Standard deviation
print(np.std(arr))  # 1.41

# Sorted
print(np.sort(arr))  # [1 2 3 4 5]

# Unique
arr_with_dupes = np.array([1, 2, 2, 3, 3, 3])
print(np.unique(arr_with_dupes))  # [1 2 3]




15
3.0
1
5
1.4142135623730951
[1 2 3 4 5]
[1 2 3]


In [8]:
## Step 4: Array Indexing & Slicing


arr = np.array([10, 20, 30, 40, 50])

# Single element (like list)
print(arr[0])  # 10
print(arr[-1])  # 50

# Slicing
print(arr[1:4])  # [20 30 40]
print(arr[:3])   # [10 20 30]
print(arr[::2])  # [10 30 50] - every 2nd element

# 2D indexing
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# weird indexing
print(arr2d[0])      # [1 2 3] - first row
print(arr2d[0][0])   # 1 - first element
print(arr2d[1, 2])   # 6 - row 1, column 2

# Boolean indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3  # [False False False True True]
print(arr[mask])  # [4 5]

10
50
[20 30 40]
[10 20 30]
[10 30 50]
[1 2 3]
1
6
[4 5]
